name: charge_wallet_sdk
description: SDK for Charge Wallet API
version: 0.0.2+9
repository: https://github.com/fuseio/charge_wallet_sdk
homepage: https://docs.chargeweb3.com/docs/overview-2
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  decimal: ^2.3.2
  dio: ^5.1.1
  freezed_annotation: ^2.2.0
  gql: ^0.14.0
  graphql: ^5.1.3
  hex: ^0.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  path: ^1.8.2
  retrofit: ^4.0.1
  web3dart: ^2.5.2
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: ^4.2.0
